# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.votingguide.org:587
mail_admin: admin@votingguide.org
mail_hostname: votingguide.org
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
