# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.dreamdefendact.org:587
mail_admin: admin@dreamdefendact.org
mail_hostname: dreamdefendact.org
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
